### ISSUE TITLE
CA1033 Interface methods should be callable by child types

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.Appclusive.Scheduler#3]
> CA1033	Interface methods should be callable by child types	
> Make 'ContractClassForIScriptInvoker' sealed (a breaking change if this class has previously shipped), implement the method non-explicitly, or implement a new method that exposes the functionality of 'IScriptInvoker.Powershell.get()' and is visible to derived classes.	biz.dfch.CS.Appclusive.Scheduler.Extensions	ContractClassForIScriptInvoker.cs	33

**Comment by rufer7** [comment]
@dfch can we close this issue as the warning did not occur during Code Analysis on solution?

**Comment by dfch** [comment]
ok
